name: newmodular
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
    mobx_watch_clean: $clean & $get & $runner watch --delete-conflicting-outputs


environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  flutter_modular: ^3.3.0
  flutter:
    sdk: flutter
  

dev_dependencies:
  modular_codegen: ^3.0.0
  mobx_codegen: ^2.0.1+3
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
